# Install pre-commit hooks via
# pre-commit install

repos:
- repo: local
  hooks:
  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ["-i"]
    exclude: &exclude_files >
      (?x)^(
        sportran/utils/obsolete/.*|
        sportran_gui/utils/tk_html_widgets/*.py|
        docs/.*|
        tests/test_cli/.*|
        examples/.*|
        setup.py|
      )$

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-executables-have-shebangs
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
    exclude: >
      (?x)^(
        tests/test_cli/.*|
        sportran/utils/obsolete/.*|
      )$
  - id: trailing-whitespace
    exclude: >
      (?x)^(
        sportran/utils/obsolete/.*|
        sportran_gui/utils/tk_html_widgets/.*py|
        docs/.*|
        tests/test_cli/.*|
        tests/test_notebooks/.*|
        examples/.*|
      )$
#
#-  repo: https://github.com/PyCQA/pylint
#   rev: v2.12.2
#   hooks:
#   - id: pylint
#     language: system
#     exclude: *exclude_files
